### ISSUE TITLE
Local host page not loading

### ISSUE THREAD

**Issue by Mdrn03** [bren1818/TCPLightingWebInterface#19]
Thank you for your work on this.  I've installed XAMPP and copied the files to the htdocs folder.  I've corrected the IP address of my TCP bridge.  I'm only needing local coverage.  However, at the stage of syncing the gateway, I go to http://localhost/ and I get this:

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at postmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/7.4.29 Server at localhost Port 80

I am running windows 10 and the only options I saw for XAMPP were for windows 8.  Is that possibly my issue?  If so, are you aware of where I can find a version of XAMPP that will work with WIndows 10?  My current version is 3.3.0

Any help on this would be greatly appreciated.  Thank you so much for your time!

**Comment by bren1818** [comment]
Hey there,

I see you closed the issue - were you able to resolve the issue? This
should work fine with the latest XAMPP or httpd on linux.

At first glance my assumption re: your error is it's likely the .htaccess
file. Renaming or removing it should resolve the issue if that's the case.

Hope you get it figured out. Happy to help if I can.

**Comment by Mdrn03** [comment]
Thank you for offering, I did exactly that and changed the port to 80 and
I'm good. Thank you!!
