### ISSUE TITLE
Single room issue

### ISSUE THREAD

**Issue by ozthegreat** [bren1818/TCPLightingWebInterface#4]
Hey,

In index.php and include.php the `$DATA = $array["gwrcmd"]["gdata"]["gip"]["room"];` variable is expecting an array of arrays, however if you only have one room setup you simply get a single array containing the values. This is easily fixed with something like:

`if ( isset( $DATA["rid"] ) )
		$DATA = array( $DATA );`

Thanks

**Comment by bren1818** [comment]
Thanks Edward, I'll look into addressing that issue.

I actually recently wiped my hub, so I think I noticed that but haven't
pushed the fix yet.

Cheers and happy Halloween 😄
