### ISSUE TITLE
Issue for posting images for use in the wiki

### ISSUE THREAD

**Issue by sktaylortrash** [bren1818/TCPLightingWebInterface#8]
![044a9aaa-09b1-11e7-8a49-42facdd3795b](https://user-images.githubusercontent.com/23568795/33867601-6c3c5bca-dec3-11e7-8683-501d1f71be68.png)
![d50a8142-09b0-11e7-816f-c34998c486c3 1](https://user-images.githubusercontent.com/23568795/33867602-6c5a7f38-dec3-11e7-848c-dcdfe043231e.png)

![untitled](https://user-images.githubusercontent.com/23568795/33867566-3e69bc42-dec3-11e7-87f3-3e8ccc7a5bd4.png)

**Comment by sktaylortrash** [comment]
![untitled](https://user-images.githubusercontent.com/23568795/33868112-aca2a7c0-dec6-11e7-87f7-1354f3e1efa5.png)

**Comment by sktaylortrash** [comment]
![footer](https://user-images.githubusercontent.com/23568795/33897902-5b109938-df2c-11e7-9ae8-687a427e29a2.png)

**Comment by sktaylortrash** [comment]
![footer-trans](https://user-images.githubusercontent.com/23568795/33898004-a87cbcc4-df2c-11e7-9c18-732f41ef5be2.png)

**Comment by sktaylortrash** [comment]
![gateway](https://user-images.githubusercontent.com/23568795/33920373-3b4bbc3e-df83-11e7-8128-8df7cbc4899d.png)

**Comment by sktaylortrash** [comment]
![myapplet](https://user-images.githubusercontent.com/23568795/34077705-04a42cde-e2d0-11e7-972e-2573eb6ceb4f.png)
![newapplet](https://user-images.githubusercontent.com/23568795/34077706-04bcc4c4-e2d0-11e7-95cd-29f6beffd739.png)
![phrase](https://user-images.githubusercontent.com/23568795/34077707-04d62c0c-e2d0-11e7-96f6-c385ab4f3efa.png)
![phrase2](https://user-images.githubusercontent.com/23568795/34077708-04ef6e10-e2d0-11e7-8ea5-aab2202859a0.png)
![service](https://user-images.githubusercontent.com/23568795/34077709-050a8b5a-e2d0-11e7-83c4-3bba3ed30c5d.png)
![that](https://user-images.githubusercontent.com/23568795/34077710-05336976-e2d0-11e7-94c9-cfd4f298cb84.png)
![thisapplet](https://user-images.githubusercontent.com/23568795/34077711-054cc77c-e2d0-11e7-9d5c-62f7e6f252ad.png)
![webhooks](https://user-images.githubusercontent.com/23568795/34077712-05661a74-e2d0-11e7-8c9c-34a92b9b5e65.png)
![webrequest](https://user-images.githubusercontent.com/23568795/34077713-057f6b32-e2d0-11e7-9c33-62c4e662e5f5.png)
![webrequestform](https://user-images.githubusercontent.com/23568795/34077714-0597c060-e2d0-11e7-9ed4-f22c443bdf61.png)

**Comment by sktaylortrash** [comment]
![querybuilder2](https://user-images.githubusercontent.com/23568795/34077783-6b793baa-e2d2-11e7-8161-2f3f617705d7.png)
![querybuilder](https://user-images.githubusercontent.com/23568795/34077778-51dd8778-e2d2-11e7-9e43-efaf468c35a2.png)

**Comment by sktaylortrash** [comment]
![untitled-1](https://user-images.githubusercontent.com/23568795/34077850-5efdfe0a-e2d3-11e7-940e-339b1db20c74.png)

**Comment by bren1818** [comment]
Haha, I never noticed you adding the images to this thread and I kept
wondering... Where/how is he uploading these!? :)

I'm starting to take on the scenes. It's... More difficult than I'd have
thought. The app does it in two steps, I'm shooting for one.

**Comment by sktaylortrash** [comment]
Yeah had to overcome the fact that you can't upload images to the wiki for some strange reason.  
Unless there's something I missed. Everything should now be fairly well documented.

Good luck on the scenes

**Comment by sktaylortrash** [comment]
[Quick Start Guide.pdf](https://github.com/bren1818/TCPLightingWebInterface/files/1566678/Quick.Start.Guide.pdf)
[Remote Lighting Kit.pdf](https://github.com/bren1818/TCPLightingWebInterface/files/1566679/Remote.Lighting.Kit.pdf)
